/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "Driver_gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*LED PD12 Blink with some delay*/


/*
 * Pointers specific to GPIO Registers*/

GPIO_Handle_t GPIOD_Handle ;

void delay(uint32_t time)
{
	for (int var = 0; var < time; ) {
		var++;
	}
}

void vLedConfig(GPIO_Handle_t *ptrGPIOD_Handle){
	ptrGPIOD_Handle->GPIO_RegConfig = GPIOD;
	ptrGPIOD_Handle->GPIO_PinConfig.GPIO_PinMode    = GPIO_MODE_OUT;
	ptrGPIOD_Handle->GPIO_PinConfig.GPIO_PinNo      = GPIO_PIN_NO_12;
	ptrGPIOD_Handle->GPIO_PinConfig.GPIO_PinOPType  = GPIO_OP_TYPE_OD;
	/*If Push Pull Config used internal pMOS-NMOS combination is used, so no PU,PD resistors required to blink LED
	ptrGPIOD_Handle->GPIO_PinConfig.GPIO_PinOPType  = GPIO_OP_TYPE_PP; */
	ptrGPIOD_Handle->GPIO_PinConfig.GPIO_PinPuPdCtr = GPIO_PIN_PU; /* With Open Drain config, use no PUPD and use External Resistor of smaller value.
																	Since inbuild Pull up resisitor is of larger value very small current willl flow
																	through LED causing LED blink in PU config with very Dim intensity.*/
	ptrGPIOD_Handle->GPIO_PinConfig.GPIO_PinSpeed   = GPIO_SPEED_MED;
	GPIO_PClkControl(ptrGPIOD_Handle->GPIO_RegConfig, ENABLE);
	GPIO_Init(ptrGPIOD_Handle);
}


int main(void)
{
	vLedConfig(&GPIOD_Handle);
	while(1)
		{
			GPIO_ToggleOutPin(GPIOD_Handle.GPIO_RegConfig, GPIO_PIN_NO_12);
			delay(500000);
		}
}


