/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Pointers specific to GPIO Registers*/

GPIO_RegDef_t * pGPIOA = GPIOA;
GPIO_RegDef_t * pGPIOB = GPIOB;
GPIO_RegDef_t * pGPIOC = GPIOC;
GPIO_RegDef_t * pGPIOD = GPIOD;
GPIO_RegDef_t * pGPIOE = GPIOE;
GPIO_RegDef_t * pGPIOF = GPIOF;
GPIO_RegDef_t * pGPIOG = GPIOG;
GPIO_RegDef_t * pGPIOH = GPIOH;


///Pending
// Clk control Reg for APB2
// NVIC IRQ Enable Register
int main(void)
{


}


